# Generated by Django 5.1.7 on 2025-03-14 15:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("mail", "0001_initial"),
    ]

    operations = [
        migrations.DeleteModel(
            name="User",
        ),
    ]
